title: John Maruska
description: >-
  Placeholder description, do not steal.
domain: johnmaruska.github.io
url: https://johnmaruska.github.io

email: jackmaruska@gmail.com
github_username: johnmaruska
bluesky_username: johnmaruska
bluesky_domain: bsky.social
linkedin_username: johnwmaruska

theme: minima
plugins:
  - jekyll-feed
